spring.application.name=voyageAI

# MongoDB
spring.data.mongodb.database=voyageAI
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Gemini API
gemini.api.key=${GEMINI_API_KEY}

jwt.secret=${JWT_SECRET}